defmodule ColdForge.Outreach.Importer do
  @moduledoc """
  Bulk-loads prospects from a CSV.

  The design goal is that you can see exactly what will happen before it
  happens. `analyze/3` does the whole import in memory and reports what would
  be created, skipped and rejected; `commit/3` then writes it. A list you paid
  for shouldn't be discovered to be half-garbage after it's already in the
  database.
  """

  NimbleCSV.define(ColdForge.Outreach.Importer.Parser, separator: ",", escape: "\"")

  alias ColdForge.Outreach
  alias ColdForge.Outreach.{Importer.Parser, Prospect}
  alias ColdForge.Repo

  # Columns we can map onto. Anything else the file carries is kept verbatim in
  # `custom_fields`, so a merge tag can reach it.
  @fields ~w(email first_name last_name company title industry phone website source notes)a

  @doc "The prospect fields a CSV column can be mapped to."
  def fields, do: @fields

  @doc """
  Reads the header row and a few sample rows, so the mapping UI can show what
  it's working with.

  Returns `{:ok, %{headers: [...], rows: [[...]], row_count: n}}`.
  """
  def inspect_csv(contents) do
    case parse(contents) do
      {:ok, [headers | rows]} ->
        {:ok, %{headers: headers, rows: Enum.take(rows, 5), row_count: length(rows)}}

      {:ok, []} ->
        {:error, :empty}

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc """
  Guesses a column mapping from the header names.

  Matching is loose — "Email Address", "email_address" and "E-mail" all mean
  the same thing, and a list bought from three places will spell it three ways.
  """
  def guess_mapping(headers) do
    headers
    |> Enum.with_index()
    |> Enum.reduce(%{}, fn {header, index}, acc ->
      case match_field(header) do
        nil -> acc
        field -> Map.put_new(acc, field, index)
      end
    end)
  end

  defp match_field(header) do
    normalized = header |> to_string() |> String.downcase() |> String.replace(~r/[^a-z]/, "")

    Enum.find_value(
      [
        {~w(email emailaddress emailaddr mail workemail), :email},
        {~w(firstname first fname givenname), :first_name},
        {~w(lastname last lname surname familyname), :last_name},
        {~w(company companyname organization organisation business account), :company},
        {~w(title jobtitle position role), :title},
        {~w(industry sector vertical trade), :industry},
        {~w(phone phonenumber telephone mobile cell), :phone},
        {~w(website url site domain web), :website},
        {~w(source leadsource origin), :source},
        {~w(notes note comments comment), :notes}
      ],
      fn {aliases, field} -> if normalized in aliases, do: field end
    )
  end

  @doc """
  Works out what importing this file would do, without writing anything.

  Every row lands in exactly one bucket:

    * `:new`        — will be created
    * `:duplicate`  — already a prospect on this project
    * `:suppressed` — on the global do-not-contact list
    * `:invalid`    — no email, or one that isn't an address

  Duplicates within the file itself count as duplicates too, so a list with the
  same address twice doesn't insert it twice.
  """
  def analyze(contents, project_id, mapping) do
    with {:ok, [_headers | rows]} <- parse(contents) do
      existing = existing_emails(project_id)

      {results, _seen} =
        Enum.map_reduce(rows, MapSet.new(), fn row, seen ->
          classify(row, mapping, existing, seen, project_id)
        end)

      {:ok,
       %{
         rows: results,
         counts: Enum.frequencies_by(results, & &1.status),
         total: length(results)
       }}
    end
  end

  defp classify(row, mapping, existing, seen, project_id) do
    attrs = row_to_attrs(row, mapping, project_id)
    email = attrs |> Map.get(:email, "") |> to_string() |> String.trim() |> String.downcase()

    status =
      cond do
        email == "" -> :invalid
        not valid_email?(email) -> :invalid
        MapSet.member?(seen, email) -> :duplicate
        MapSet.member?(existing, email) -> :duplicate
        Outreach.suppressed?(email) -> :suppressed
        true -> :new
      end

    result = %{status: status, email: email, attrs: attrs, raw: row}
    {result, MapSet.put(seen, email)}
  end

  @doc """
  Inserts the rows `analyze/3` marked `:new`.

  Insert-per-row inside one transaction rather than `insert_all`: prospects
  need their unsubscribe token generated by the changeset, and a row that fails
  validation should be reported rather than aborting the file.
  """
  def commit(contents, project_id, mapping) do
    with {:ok, analysis} <- analyze(contents, project_id, mapping) do
      {inserted, failed} =
        analysis.rows
        |> Enum.filter(&(&1.status == :new))
        |> Enum.reduce({0, []}, fn row, {ok, errors} ->
          case Outreach.create_prospect(row.attrs) do
            {:ok, _prospect} -> {ok + 1, errors}
            {:error, changeset} -> {ok, [{row.email, changeset} | errors]}
          end
        end)

      {:ok,
       %{
         inserted: inserted,
         failed: Enum.reverse(failed),
         skipped: analysis.total - inserted - length(failed)
       }}
    end
  end

  defp row_to_attrs(row, mapping, project_id) do
    mapped =
      Enum.reduce(@fields, %{}, fn field, acc ->
        case Map.get(mapping, field) do
          nil -> acc
          index -> Map.put(acc, field, row |> Enum.at(index) |> normalize())
        end
      end)

    mapped
    |> Map.put(:project_id, project_id)
    |> Map.put(:custom_fields, custom_fields(row, mapping))
  end

  # Columns nobody mapped are still worth keeping — they're what a merge tag
  # like {{roof_type}} would reach for.
  defp custom_fields(row, mapping) do
    mapped_indexes = mapping |> Map.values() |> MapSet.new()

    case Map.get(mapping, :__headers__) do
      nil ->
        %{}

      headers ->
        headers
        |> Enum.with_index()
        |> Enum.reject(fn {_h, i} -> MapSet.member?(mapped_indexes, i) end)
        |> Enum.reduce(%{}, fn {header, index}, acc ->
          case row |> Enum.at(index) |> normalize() do
            nil -> acc
            "" -> acc
            value -> Map.put(acc, slugify_header(header), value)
          end
        end)
    end
  end

  defp slugify_header(header) do
    header
    |> to_string()
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9]+/, "_")
    |> String.trim("_")
  end

  defp normalize(nil), do: nil

  defp normalize(value) do
    case value |> to_string() |> String.trim() do
      "" -> nil
      trimmed -> trimmed
    end
  end

  defp valid_email?(email), do: Regex.match?(~r/^[^@,;\s]+@[^@,;\s]+\.[^@,;\s]+$/, email)

  defp existing_emails(project_id) do
    import Ecto.Query

    Prospect
    |> where([p], p.project_id == ^project_id)
    |> select([p], p.email)
    |> Repo.all()
    |> Enum.map(&String.downcase/1)
    |> MapSet.new()
  end

  # A malformed CSV raises out of NimbleCSV; the operator gets a message rather
  # than a 500 page.
  defp parse(contents) do
    {:ok, Parser.parse_string(contents, skip_headers: false)}
  rescue
    error -> {:error, Exception.message(error)}
  end
end
