defmodule ColdForgeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :cold_forge

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_cold_forge_key",
    signing_salt: "TIZP4OPY",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :cold_forge,
    gzip: not code_reloading?,
    only: ColdForgeWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Uploads are served from their own directory rather than out of `priv`,
  # which a release stores under a versioned path that changes on every deploy.
  # Resolved at request time, since the directory is runtime configuration.
  plug Plug.Static,
    at: "/uploads",
    from: {ColdForge.Uploads, :dir, []},
    gzip: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :cold_forge
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Must run before the parsers: SNS sends JSON labelled text/plain, which the
  # JSON parser would otherwise skip, leaving the body undecoded.
  plug ColdForgeWeb.Plugs.SNSContentType

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ColdForgeWeb.Router
end
